### ISSUE TITLE
Plugin to use Neo4j within Jupyter notebooks

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/serenata-de-amor#101]
This is not an issue that will generate code for Serenata de Amor, but will create a while new package.

Using graph database will help in Serenata de Ampr us and I ran into @nicolewhite's repo that makes great dataviz using Neo4j inside Jupyter notebooks (check this [example](http://nicolewhite.github.io/neo4j-jupyter/hello-world.html) and the main [repo](https://github.com/nicolewhite/neo4j-jupyter)).

My idea (and via tweet Nicole's said she's fine with that) is to pack her code into a package instalable via `pip`. Adding the module to Serenata de Amor repo and we can use the dataviz in out notebook. That's the idea.

**Comment by cuducos** [comment]
I started to adapt the code but I couldn't get back to it (it's **not** working). I have this work in progress though https://github.com/cuducos/neo4jupyter

**Comment by Gusbru** [comment]
I managed how to do Neo4j works. I am preparing a documentation together with a jupyter notebook explaining which packages are necessary together with the "Hello world" program.

**Comment by cuducos** [comment]
Many thanks, @Gusbru — that's very helpful ; )

**Comment by vmesel** [comment]
@renanpalmeira can you help us?

**Comment by RenanPalmeira** [comment]
@vmesel @cuducos I know a few plugins for neo4j with Jupyter, but never used. I have a simple project (a simple ORM) above the Neo4j with python https://github.com/RenanPalmeira/pyneo4j. Nothing prevents us from creating a plugin for jupyter.

About Neo4j in Serenata de amor, The perfect ideia because the government itself uses neo4j to look for irregularities (https://www.infoq.com/br/presentations/big-data-no-planalto-como-o-governo-minera-datasets).

I use Neo4j in production long ago, I can help in to model in Neo4j and in plugin jupyter.

**Comment by cuducos** [comment]
If you can test any of these plugins, addind the instructions to
CONTRIBUTING.md and (maybe) an example Jupyter Notebook this issue is
closed ; )

**Comment by marcusrehm** [comment]
Hey guys, I played with it for a while and created a branch [here](https://github.com/marcusrehm/serenata-de-amor/tree/neo4j).

I updated the [CONTRIBUTING.MD](https://github.com/marcusrehm/serenata-de-amor/blob/neo4j/CONTRIBUTING.md#using-neo4j-in-graph-analysis) to show how to put Neo4j running with Docker and created 2 notebooks using it.

The first one is actually Nicole's hello world notebook and the second one I created using some of datasets from project.

I needed to tweak Nicole's code in order to workaround 2 points:
- There is a check in [vis.py](https://github.com/marcusrehm/serenata-de-amor/blob/neo4j/develop/scripts/vis.py#L66) to ensure that `figure` folder exists and if not creates it. This folder is where the graphs are stored.
- The second was an [optional parameter in draw function](https://github.com/marcusrehm/serenata-de-amor/blob/neo4j/develop/scripts/vis.py#L76) passing a graph's name in order that files stored in `figure` can have legible names.

In the end I'm still having trouble with igraph and jgraph plotting libraries, but vis library and networkx are both ok.

My concern in create a package with vis library is that it relies on some javascript inside `/lib` folder and until now I have not figure out how to embed it in a python package and be able to call it from notebooks or html. :) The folders `scripts` and `lib` are available inside `/develop` folder.

/cc @cuducos @Gusbru @RenanPalmeira

**Comment by cuducos** [comment]
Hi @marcusrehm — great work! Many thanks.

My comments try to point in the direction of how to incorporate Neo4j for good in this repo. Even if you're not up to follow this path, you branch is awesome in showing the path ; )

> I updated the CONTRIBUTING.MD to show how to put Neo4j running with Docker and created 2 notebooks using it.

I think that this should be added in the `Dockerfile` itself, or move stuff to `docker-compose.yml`. Also it would be great to have it available for non-Docker users (even if we just add a link _install Neo4J_ pointing to their install instructions).

> Unfortunately with the vis library the notebooks doesn't show the graphs in Github, just the ones created with `networkx`. I'm looking for ways to render html inline and not as a iframe as the library does now. 

That would be awesome, (but not strictly necessary…).

> My concern in create a package with vis library is that it relies on some javascript inside /lib folder and until now I have not figure out how to embed it in a python package and be able to call it from notebooks or html.

Vis is a node package — either we install it using `npm install vis` or we can just clone it from https://github.com/almende/vis in our setup script — does that help?

**Comment by marcusrehm** [comment]
>I think that this should be added in the Dockerfile itself, or move stuff to docker-compose.yml. Also it would be great to have it available for non-Docker users (even if we just add a link install Neo4J pointing to their install instructions).

I added a link in [CONTRIBUTING.MD](https://github.com/marcusrehm/serenata-de-amor/blob/neo4j/CONTRIBUTING.md#using-neo4j-in-graph-analysis) to Neo4j website for download and installation for non-docker users.
About the Docker part I think I will need some help with that... :) Maybe I can chat with you guys or somebody could point me the best way.

>That would be awesome, (but not strictly necessary…).

This one is tricky indeed. I think we can let it for a future release of the package ok?

>Vis is a node package — either we install it using npm install vis or we can just clone it from https://github.com/almende/vis in our setup script — does that help?

Actually you show me the path my friend! :) At vis repo they say that it is available at http://cdnjs.com/, so I just changed the script to get css and js files from there. Now there is no need for the `/lib` folder. I removed it from the project.

About the package, I created it locally but I would like to know if you guys already have a name for it or want to put additional information on that. I was thinking of create a repo so you can fork it and publish in Serenata de Amor account at PyPI. What do you think?

**Comment by marcusrehm** [comment]
Guys, I finished the updates and the `neo4jpyter` package integration also. In fact, a package named `neo4jupyter` already existed in Pypi, but I was having some issues to run it. I fixed it, but for now I pointed the neo4j_requirements.txt to my [repo](https://github.com/marcusrehm/neo4jupyter) so when the owner of main repo accept the PR I will change the requirements file to point to Pypi ok?

This version doesn't need a folder to hold graph files, all the code is embedded into notebook. Unfortunately the java script don't run on Github, so in order to view the graphs you need to download and run the notebook.

The Docker part I finished the docker-compose for neo4j but I need to update CONTRIBUTING.MD yet. About requirements file for neo4j, do you think we can put it in requirements.txt? I think it would help the workflow when someone try to use it after have been using serenata de amor.

/cc @cuducos

**Comment by marcusrehm** [comment]
Finished the docker-compose-neo4j.yml. PR #200 created. :)

/cc @cuducos

**Comment by cuducos** [comment]
That's great work! Really. Gonna keep the discussion in the PR from now ; ) Many thanks, @marcusrehm!
