### ISSUE TITLE
CONTRIBUTING.md - Other languages

### ISSUE THREAD

**Issue by fcevado** [datasciencebr/serenata-de-amor#130]
There isn't any guideline to contribute with code in other languages. I know that are some mentions on contributing with other languages in issues/pr( #79, #73 and #52), but as I said there isn't any instructions on how to contribute with other languages code.

Given the structure of the project, I think the first limitation would be to work with [jupyter](https://jupyter.org/). Another one would be the focus on mathematical precision(due to the nature of the project per se).

**Comment by cuducos** [comment]
Hi @fcevado,

I'm not a data science specialist so I'll tag @irio to invite him to this discussion. Maybe he can me more precise than I am when it comes to mathematical precision — although I'm not concerned with NumPy for this project.

Anyway I strongly disagree with you when you say a _limitation would be to work with jupyter_. Actually I'd say the opposite: A very strong side of this project is the fact that it works with Jupyter Notebook.

First of all this project means nothing without a strong focus on communication (whether it is with the general public, the media or the judiciary). It's aim is to fight corruption and data science is our mean to achieve that (i.e. fighting corruption is not a side effect of excelling in data science). That said Jupyter Notebook is a good tool to develop analysis **and** for non tech people (people focused on communication) read the analysis without any need of an extra layer (data scientists don't need to write reports, communication people can read the notebooks without needing the tech stack and knowledge — which make s a lot of sense specially for a 2 months sprint, which is our case right now).

Second, we're open source and we want to get a wide range of contributors engaged with the project — it makes sense not bacause it's _our project_, but because it's _our country_. Jupyter Notebook is an easy entry point for beginners. The other weekend we had a sprint in Ribeirão Preto. A guy that has never heard of Pandas or Jupyter before could commit three notebooks after the weekend sprint (see #111). More experienced people would get the workflow even easier and use their preferred languages within Jupyter Notebook (as @pingfreud did with R in #52 or [with Julia](https://github.com/JuliaLang/IJulia.jl) as you've found out)

I'd also invite @pingfreud to this discussion. As he started to work with R in Jupyter Notebook maybe he has something to add (in favor of my argument or not).

So I do understand that this might no be more precise and professional stack, but I see a lot of positives in embracing Anaconda Python (with NumPy and Pandas) together with Jupyter in the context of this project.

Does that make sense?

**Comment by cuducos** [comment]
Rereading this topic I see that I forgot one important issue: we might add to the `CONTRIBUTING.md` that it is possible to contribute with other languages such as R or Julia within Jupyter Notebooks.

**Comment by fcevado** [comment]
Sorry, I didn't say "limitation" meaning limitation of the project, but as a limitation for possible languages to work with the project. I was pointing what could be possible guidelines for contributors to use other languages.

I think this guidelines should cover code organization, how to integrate new languages with the project and what would be necessary for code to run. Since python is mostly covered with Anaconda Python, it seems unnecessary to cover some of this guidelines, but with new languages integrating the project it can become a mess really fast.

**Comment by ebonet** [comment]
I would argue that Jupyter should not only be advised to use, but also mandatory. The reason for that is when dealing with Data Science we SHOULD be able to reproduce data analysis made by the original author. 

On a second python, jupyter is not python. You can run notebooks in python, scala, R, and 40 other languages. You just need to change the [kernel](http://jupyter.readthedocs.io/en/latest/projects/kernels.html). On the downside having too many languages on the project can make it hard to be maintained to the long run.

**Comment by cuducos** [comment]
I think I'll leave this as it is and treat newcomers as they knock our doors. We have two people developing in R and Julia and before merging their commit we asked them to add instructions to the `CONTRIBUTING.md` regarding the setup for the languages they used in the notebook.
