### ISSUE TITLE
List of advisors of each congressperson

### ISSUE THREAD

**Issue by Irio** [datasciencebr/serenata-de-amor#139]
Scrape from the Chamber of Deputies' site, [as suggested by Fernando Noronha](https://www.youtube.com/watch?v=_E6Iwm9MMKI&lc=z12yunpwvmjagnywb04cft2pxxjkzpv4fuk0k).

http://www2.camara.leg.br/transparencia/recursos-humanos/quadro-remuneratorio/consulta-secretarios-parlamentares/layouts_transpar_quadroremuner_consultaSecretariosParlamentares

It's a dependency of https://github.com/datasciencebr/serenata-de-amor/issues/138.

**Comment by bruno-schmidt** [comment]
Hello guys! Did anybody tried to solve this issue yet?

I tried something last night. Please, take a look: https://github.com/bruno-schmidt/sda-advisors-scrapper

The code is a shame, I'm sorry. I'm beginning to learn all this stuff with javascript, so it might look ugly.  

Please let me know if it helps!

Important: it takes some (really some) time to scrap all the data! I didn't try it yet because I've been experiencing connection issues, but I will try again soon.

**Comment by cuducos** [comment]
Many thanks, @bruno-schmidt.

If your issue is performance, bear in mind that you're making ~514 requests and yes, requesting, treating the response, writing data are steps that take time. That said my comments here are code-wise (not data wise, I haven't check that part yet).

From my tiny experience in this project multiprocessing helps, but what really enhances performance in scripts like yours  is parallelizing the requests (our first bottleneck isn't the processor, it is the amount of requests in our imaginary queue). I've been playing around with [grequests](https://github.com/kennethreitz/grequests) (that's not a typo, that's [gevent](http://www.gevent.org) + [requests](http://docs.python-requests.org/)). Maybe you can pack a group of requests and start them all in parallel. 

Multiprocessing workers are limited by the processor (usually 2 or 4, max. 8 for a common computer). But more than 8 requests can happen in parallel without being an hassle to the processor.

An alternative might be using [Scrapy framework](https://scrapy.org) — they optimize lots of things for performance (and their focus is surely scrapping data). But this might be too much: you're script is already in good shape, I wouldn't rewrite everything in the scrapy framework at this point.

Let me know if this makes sense. I might be available for pairing one of these days if you want — just drop a line.

**Comment by bruno-schmidt** [comment]
Thank you @cuducos!

It really makes sense. I made some research again and rewrote some code using grequests as you suggested. It's running considerable faster!

The repository is updated with the new code! [Here :D](https://github.com/bruno-schmidt/sda-dep-advisors)

**Comment by cuducos** [comment]
That's great news! I re-read your code and it looks great, well documented, yay! Are you willing to send a PR to this repo? If you are, once you've done it I start code reviewing it. Or alternatively these are the thing I can remember from the top of my head:

- Is there a way to fetch advisors of deputies from previous terms? We have their numbers in our database, but we should check if the URL/POST request gives data from the previous terms.
- Why is the list of advisors limites to four?
- And, as a suggestion, you can enhance a lot the logic/readability/clarity of your script using [`csv.DictWriter`](https://docs.python.org/3/library/csv.html?highlight=dictwriter#csv.DictWriter) instead of lists and the default CSV writer ; )

**Comment by bruno-schmidt** [comment]
Hello! Thank you for your feedback @cuducos !

I fear we can only fetch the advisors from the current term with the URL post by Irio. :disappointed: 

As you suggested, I changed the function to use `csv.DictWriter`. It feels better now! 

Also, I was late to notice that some deputies has more than 20 advisors, causing the page to have pagination. I pushed a new version and sent a PR! I fear the code is a bit ugly now. Please tell me if I can improve anything!

Should we continue this conversation here or in the PR?

**Comment by cuducos** [comment]
> Should we continue this conversation here or in the PR?

Sorry, I missed the thread here. Gonna re-read your code and move the conversation to the PR.

**Comment by Irio** [comment]
@bruno-schmidt The current state of your code seems to be enough to generate a first version of the dataset. Want to open a pull request so we can work on collecting it and putting into our dataset list?

**Comment by cuducos** [comment]
@irio #149

**Comment by bruno-schmidt** [comment]
@Irio yes! as @cuducos said, it's PR #149

**Comment by jtemporal** [comment]
I merged the PR with the script into master so we can get going on generating the new dataset ;)

**Comment by cuducos** [comment]
Closed by ba55eb7ffae8083c11044b0f60b89415a44bfe6d
