### ISSUE TITLE
Centralized database of information

### ISSUE THREAD

**Issue by thiagobrito** [datasciencebr/serenata-de-amor#160]
Hello folks,

I've been looking a way to contribute to your project and man, there is a lot of work that we'll have in this brave future!

So I have a suggestion about the database, we have the directory "src" where we fetch a lot of data from some sources. The first thing that I tried was to create a scraper for www.consultasocio.com, that was easy until they block my connection to the site in order to avoid... well... scrappers.

So I started to think that the model that we are working is nice but not so sustainable in the long term. We should create a centralized database with all the information that we can collect about the congress people, their family, companies and so on, we need to put on a single server and be easy to download the full database, query a single information and update with new information that we need.

For example, in the issue #98, we are working on an algorithm that gives the probability of a certain partner is a relative of the congressperson. Man, this is awesome!! But we need to collect this information and store in some place where everyone could check and move forward.

If we do this, I think that a lot of issues will be done really faster and the Rosie could use all this information too!

What do you think about this guys? Is it a good idea? I also have a suggestion for the database name that is "Dossie". We can also create a system that everyone could update this database collaboratively and in an easy way because some information is hard to collect in an automated way.

**Comment by cuducos** [comment]
Hi @thiagobrito — many thanks for sharing uour ideas and for your enthusiasm.

The short version of my comment is: we don't need a centralized database, we need a centralized way to obtain the database. And — good news — we already have it, take a look in the serenata-toolbox repo ; )

In fact all datasets are already (as you suggested) in a single server and are easily downloaded in a single command. And that's the best we get. To keep it (relatively short) the main issue at sake as a principle in data science project called reproducibility — every single analysis made here should be reproductible is by any other person, from collecting data to reaching the findings. If we centralize the database will end up with a massive file that would require a lot of hardware to to handle it (this imposes unnecessary restrictions in my point of view), we'll have an overhead to keep all sources clear, and have a single dataset would break reproductibility (once we push new data in, previous notebooks will change if re-run). That's a good summary of why we're versioning each dataset. Does that make sense?

Finally maybe the _Dossie_ idea is mostly a data visualization possibility (not an architectural one) — what do you think about it?

**Comment by thiagobrito** [comment]
Hello @cuducos, thanks for the fast response!

When we have a database that is already available to download from some place (Ex.: Ceap Dataset), for me it's fine. That's a good think.

But for example, in the case of the issue #18, we have a deeper problem. We need to figure out how to collect information from www.consultasocio.com, in order to identify who is the partner of the congressman and what companies belong to him, we also need to know who are the relatives of the target, we don't have this database available in any place yet.

In this case, the database is not so big and I think that when we create the information it won't change (only if the person opens a new company for example and that's good!).

I agree that this could be a data visualization possibility too. But I believe that we have a big problem about the information available in order to make the analysis faster.

Is it possible to create custom databases and put this data inside the directory "data" inside github? Or put this database file inside www.datasciencebr.com to be downloaded when needed?

**Comment by cuducos** [comment]
> In this case, the database is not so big and I think that when we create the information it won't change 

I tend to disagree.

```console
>>> import this
The Zen of Python, by Tim Peters

…
Special cases aren't special enough to break the rules.
…
```

> But I believe that we have a big problem about the information available in order to make the analysis faster.

I'm not sure what you mean.

One the one hand you just said _When we have a database that is already available to download from some place …for me it's fine)_ — and we have that at [the toolbox](https://github.com/datasciencebr/serenata-toolbox).

On the other hand, as this is a live project part of it is the analysis but another important bit is [data collection](https://github.com/datasciencebr/serenata-de-amor/issues?q=is%3Aopen+is%3Aissue+label%3A%22data+collection%22). So I think that's the way it is. We discussing strategies to mine/scrap/get data is a crucial step of things like #18 — that's the way it is.

BTW a lot of people have already tried Consulta Socio, but they're not friendly with bots (see their [terms](http://www.consultasocio.com/sobre)). Maybe getting in touch with them offering a partnership could work better.

> Is it possible to create custom databases and put this data inside the directory "data" inside github?

Yes, but this would compromise the reproducibility principle I told you before. So we don't do it, we follow the best practices in data science.

> Or put this database file inside www.datasciencebr.com to be downloaded when needed?

That's basically what we've done, but we used a AWS S3 — you can simply run [`datasets.fetch`with the toolbox](https://github.com/datasciencebr/serenata-toolbox/blob/master/serenata_toolbox/datasets.py) and get all datasets (or yet  you can figure out the direct URLs form that script, it's piece of cake).

**Comment by thiagobrito** [comment]
Ok.

**Comment by Irio** [comment]
I see your point, @thiagobrito. As a frequent contributor in all Serenata de Amor's projects, sometimes I miss a single place to see all of our data. Specially when just having a glance of everything we already collected. How large is our database? What columns each dataset has? Where's the documentation for dataset X version Y? How many records were added between version X and Y of this dataset? I usually create a quick and dirty Jupyter Notebook (sometimes hosted in my Gist profile) to give these answers for people I'm presenting the project.

Nowadays, this "single place" is the `data` directory of this repository, which is gitignored because tends to grow very quickly (my own has 5.99GB), since contains multiple versions of the same database for reproducibility purposes as explained by @cuducos.

If we're talking about the same problem, a solution I see is creating a portal like http://dados.gov.br/ or https://datahub.io/. Automatically synced with our Amazon S3 bucket, containing all datasets versions with their docs, when available. Files could be easily downloaded from there, though we would still ask people to use `scr` to download them directly from S3 - remaining it as the option with less setup therefore more accessible to new contributors. Much easier downloading a CSV and reading it using just Pandas than learning how to deal with something like a Hive infrastructure and connectors.

**Comment by carlosbaia** [comment]
I agree with @thiagobrito,  www.consultasocio.com is a good example, you need a robot  to collect data from all politicians, their families and all associates in all companies. That crawler will take hours, if theirs have lots of companies and associates, maybe, can take days.
Will everybody need wait for days to collect this again?

If I create a robot to get the family from Facebook relationship (some of than are public), that will take weeks.
Will everybody need wait for weeks to collect this again?

Or you watch on TV, somebody is uncle from some politicians, everybody need remember to put this in a private database? Is somebody forget or don’t see on TV, this person will have less data to discover new things.

Some important information, probably the most important ones, will be this kind of information and not in plug and play databases.

I agree the source of information and all the process must be reproducible, so, we can put  the code to generate this information published, but we can have the data source too. If somebody have some doubt, can run and wait the necessary time to confirm the information.

**Comment by thiagobrito** [comment]
@Irio I think that we need a way to centralize our databases in order to be easy to put more information about everyone even if this database is big.

I'm creating a database with all the information that we need to solve the issue #18 and this is the perfect situation that is necessary to create a single database that is customized and hard to create, but must be easy to download and update in order to be used by us.

Now I'm creating a single JSON file with this information but this is a situation where if we grow this information collaboratively in the future we can find more and more applications and useful patterns.

@carlosbaia this is exacly what I'm saying. In the future anyone can put any information about public person and we can use this in order to get more and more patterns. Man, this could be huge!

**Comment by pmargreff** [comment]
@thiagobrito Nosql?

**Comment by thiagobrito** [comment]
@pmargreff yes, it's the easiest way to start. You request a CNPJ or congressman name and you get a JSON with all his information. Simple as that.

**Comment by chessbr** [comment]
I guess @thiagobrito looks for an API to send processed datasets right? (or almost that) something like this dataset database: http://archive.ics.uci.edu/ml/index.php

The main issue is because this project needs extremely transparency, sending data without the source or without the "formula" to extract the data could make this project questionable 

From where http://www.consultasocio.com take its data? Is that true? Is it reliable? Scrapping data from public organizations is the best way to do this IMO. That site extracted info from some public organization and we could do that too.

However, I have the same feeling about a central data so we can create applications to summarize it on a "fast" way, but due the nature of this project, at least at this moment, that is good way to go.

I will suggest some Dashboard feature which should take processed data from the datasets (as it is presented on the main page of this project).

**Comment by cuducos** [comment]
Thanks for the  jumping in, @chessbr. I think I get your point, but just to clarify one detail:

> The main issue is because this project needs extremely transparency, sending data without the source or without the "formula" to extract the data could make this project questionable

That's exactly what we **don't** do: actually we send no data at all, and the data we use anyone can gather and process is from the source with [the toolbox](https://github.com/datasciencebr/serenata-toolbox) — the toolbox shoes exactly the source we download data from, how we process it and how we get to the datasets used here. Does that make sense?

**Comment by chessbr** [comment]
Yes it does, that is why I said that scrapping data from not trusted source is not a good idea :)

**Comment by cuducos** [comment]
Closed by inactivity — anyone is free to re-open and suggest new strategies and architecture feasible for us ; )
