### ISSUE TITLE
Collect average real estate prices per squared meter by region 

### ISSUE THREAD

**Issue by hyena22** [datasciencebr/serenata-de-amor#20]
Retrieve estimated prices per squared meter in order to compare against declared expenses for rents by scraping from http://seriesestatisticas.ibge.gov.br/series.aspx?vcodigo=PRECO415.

**Comment by janosimas** [comment]
I was looking in some other sites that can give some information on this:
http://www.agenteimovel.com.br/mercado-imobiliario/a-venda/sao-paulo,sp/
http://www.zapimoveis.com.br/quanto-vale-este-imovel-mapa-dos-precos/

**Comment by luizpericolo** [comment]
@janosimas 

The first site looks really scrapable. It would be easy to build "all possible urls" to collect and save the average real estate price and no further computation would be needed since the site already returns this information. And the site returns information by neighborhood. It might not be as granular as @cuducos commented on PR #27, but it is better than having an average price by state.

The second site would be a bit harder in my opinion. Searching for some neighborhoods here in Rio and checking the response that is rendered to the map you get entries like this:

    {
  	   "AreaUtil": null 
	   "Coordenadas": {
		   "Latitude": -22.902176,
		   "Longitude": -43.280269
	   }
	   "DataUltimoAnuncio": null
	   "Dormitorios": null
	   "Endereco": null
	   "ID": 73390
	   "PrecoM2": null
	   "PrecoVenda": 271362.8263
    }

It neither returns a value for "PrecoM2" (price by square meter) nor a value for "AreaUtil" (that means something like built area). That means we don't really have information about price for square meter for any real estate and we can't calculate it either. Aside from that the body of the POST that is sent for this API relies on long and lat coordinates.

**Comment by Lrcezimbra** [comment]
Looking in ZAP Imoveis, I found that search for 'estates for rent' instead of 'estates for sale', solve the problem cited by @luizpericolo, the response has a rental price (PrecoLocacao) that we can use:
```json
{
	'AreaUtil': None,
	'Coordenadas': {
		'Latitude': -30.0332536, 
		'Longitude': -51.2152337
	},
	'DataUltimoAnuncio': None,
	'Dormitorios': None,
	'Endereco': None,
	'ID': 10779682,
	'NotaLocacao': 19.2896946427,
	'NotaVenda': 0,
	'PrecoLocacao': 6500,
	'PrecoM2': None,
	'PrecoVenda': None,
	'TipoOfertaID': 2,
	'indOferta': True
}
```
With coordinates it's possible to get the address. 

And with ID we can get details about estate like "AreaTotal", "AreaUtil", etc:
```json
{
	'AreaTotal': 100,
	'AreaUtil': 100,
	'Bairro': 'BOM FIM',
	'Dormitorios': 0,
	'DormitoriosMaxima': None,
	'EstagioObra': 0,
	'FotoPrincipal': 'http://imagens.zapcorp.com.br/2594410/3056797f-224c-4cf7-8307-9b4834b403fb{tipo}.jpg',
	'ID': 10779682,
	'IndDistrato': False,
	'PrecoLocacao': 6500,
	'PrecoVenda': None,
	'SubTipoImovel': 'Loja/Salão',
	'SubTipoOferta': 2,
	'Suites': 0,
	'SuitesMaxima': None,
	'TipoOfertaID': 2,
	'Vagas': 0,
	'VagasMaxima': None
}
```

I created a [simple script](https://gist.github.com/Lrcezimbra/8a8a4e35c8e5fb79be4b3f2df18e7cf2), just for tests, that get and print some estates. If it can be used for the project I can create a script to fetch the data.

**Comment by cuducos** [comment]
Wow… IMHO that's such an useful dataset to match with housing/accommodation expenses. Thanks for that.

I'm just not sure about which data to use for the scrapping. Real state prices in congressman origin, Brasília or what? Any ideas @Irio?

**Comment by cuducos** [comment]
I think PR #100 covers that, so I'm closing this issue.

**Comment by ebonet** [comment]
As addition, one could also get the real state data from [VivaReal](https://www.vivareal.com.br/). I've done it [on a personal project](https://github.com/ebonet/floripaaluguel/blob/master/prepare.py).
