### ISSUE TITLE
Datavzi with Tableau

### ISSUE THREAD

**Issue by giorgecaique** [datasciencebr/serenata-de-amor#282]
_[Translated version of the original message]_ 

I'm working with data from the Chamber of Deputies in on a classroom project at my university. I've created a data visualization with Tableau. The project is at a very early stage yet but it generates relevant insights to people. If I anyhow (I/the project) could contribute to this project, that would be great. This is the link https://public.tableau.com/profile/giorge.caique#!/vizhome/Oraculum_Deputados/MainDashboard

---

_[Original message]_

Estou trabalhando em um projeto da faculdade com a base de dados da Câmara dos Deputados e criei uma visualização com o Tableau. O projeto está em fase inicial, mas já consegue gerar informações relevantes para a população. Se puder contribuir de alguma forma com o projeto, seria ótimo! Segue o link: https://public.tableau.com/profile/giorge.caique#!/vizhome/Oraculum_Deputados/MainDashboard

**Comment by cuducos** [comment]
Hi @giorgecaique, as the official language of the project is in English I'm editing your message, ok?

**Comment by cuducos** [comment]
Now, general comments:

As discussed in several other issues around here I see some problems with the kind of dataviz you're working on:

* Total by parties: politicians in general change parties very often in Brazil so I don't know exactly how to interpret this data… yet parties have different distribution in the House, so it is indeed expected, for example, to have a higher amount of expenses from PMDB when compared with DEM.
* Total by state: the total of the quota is different depending on the state of the congressperson, and the number of representatives varies a lot among states… so again, I'm not sure about what this data tell us about the usage of public funds.
* Devil image: the bill regulating the usage of the quota says that some values can be accumulated in the fiscal year, so it is kind of harsh IMHO to illustrate this chart that way (it sounds as a heavy accusation for something that might not be illegal at all)

In spite of that the other charts are very instructive: particularly I really like one on the subquotas (categories such as telecoms, publicity etc) and on the main companies getting the money from this quota. Following on that I would consider a filter by suquota as (for examples, so I could see othermain players in different subquotas).

Anyway… great job! Feel free to browse the project and jump in any issue.

As this issue is pretty open on its intent I'll let it here because discussion can bring insights to both projects, but we might close it for inactivity one of these days ; )

**Comment by giorgecaique** [comment]
> Total by parties: politicians in general change parties very often in Brazil so I don't know exactly how to interpret this data… yet parties have different distribution in the House, so it is indeed expected, for example, to have a higher amount of expenses from PMDB when compared with DEM.

How do you think I can improve this? Should I normalize the data for me to compare how the parties are spending the money? 

Same thing for the Total by state, if I normalize the data and put every state in the same scale (based on each one reality) would you consider this chart more relevant?

When I created this chart, my intention was to show how much money was spended by the parties, but I see your point and I also can see that this can lead to a wrong interpretation (I don't want this).

> Devil image: the bill regulating the usage of the quota says that some values can be accumulated in the fiscal year, so it is kind of harsh IMHO to illustrate this chart that way (it sounds as a heavy accusation for something that might not be illegal at all)

I didn't know about this. I'll search for info about the fiscal year so I can show the right interpreation in my viz.

I'll work on the improvements that we spoke about and keep showing the progress of the project. Hope I can help your project with some insights.

Thank you for your reply and your feedback. It was really helpfull. :D

**Comment by cuducos** [comment]
> Same thing for the Total by state, if I normalize the data and put every state in the same scale (based on each one reality) would you consider this chart more relevant?

Sure thing ; ) I mean… it depends on how you normalize, but it is totally feasible ; )

Beyond that, hell yeah! Keep on with the great project!

**Comment by cuducos** [comment]
Closed by inactivity
