### ISSUE TITLE
Negative expenses on the dataset

### ISSUE THREAD

**Issue by andrepinho** [datasciencebr/serenata-de-amor#29]
[@Irio 's descriptive analysis](https://github.com/datasciencebr/serenata-de-amor/blob/master/develop/2016-08-13-im-descriptive-analysis.ipynb) shows that we have documents with negative `net_value` in `2016-08-08-last-year.xz` dataset. All of them are flight tickets issued but not used by the congressperson.

My hypothesis is: for each of those documents there must be a corresponding document with a positive `net_value` where the flight ticket was first issued.

It can easily be proved since `document_number` should be the same for both documents.
One thing to keep in mind is that flight companies usually don't offer full reimbursement. That means the negative values will often be smaller than their positive counterpart (well, they're negative, but you get what I mean).

I think it's important to validate this because negative values without a corresponding positive one can hurt the accuracy of calculations regarding `net_value`.

**Comment by c4rl0sm3nd3s** [comment]
Hi there,

I asked at Chamber of Deputies about what really happens to the "bilhete de compensação", because it is not clear that the negative value is really returned to the House or if it is somehow a open credit, so the Deputy could use later that amount for another reason (since it is already paid).

the protocol number is BAE9103619929 at http://www2.camara.leg.br/participe/fale-com-a-ouvidoria/fale_conosco_acompanhar_mensagem

I update here when I have some feedback from them.
thanks

**Comment by andrepinho** [comment]
Hi @c4rl0sm3nd3s

Thanks for asking the Chamber and sharing with us. AFAIK, we really don't have an official statement regarding this issue. We've been just assuming that the congress person cancels the flight and then returns the money he received from the Flight Company.
Usually a reimbursement is less money than the purchase due to cancellation costs but I've seen it being higher. Maybe due to currency exchange rate? Not sure.
Have you seen my [PR](https://github.com/datasciencebr/serenata-de-amor/pull/66) about it? It's still a work in progress, but it show at least a little of how those flight reimbursements look like in the data.

**Comment by c4rl0sm3nd3s** [comment]
I was doing some research and I found this 
![screen shot 2016-10-20 at 12 35 45 am](https://cloud.githubusercontent.com/assets/658836/19546374/4639bbe8-965d-11e6-80df-39e81d6bf309.png)

As you can see, all results has the same 'document_number' , in my sql db I use the same name as the xml, so column it is the 'txtNumero'. 

Maybe all the results should be used as one receipt, sum all and the result, if it is a positive value will be the 'net_value'.  

what do you think?

**Comment by weslleymberg** [comment]
@c4rl0sm3nd3s do you remember the `installment` (`numParcela`) value for these rows? (If don't, I can take a look later)
Because, if I'm not wrong, the reimbursement can occur in portions so in these cases would make sense to sum up the values.

**Comment by c4rl0sm3nd3s** [comment]
![screen shot 2016-10-20 at 7 31 56 am](https://cloud.githubusercontent.com/assets/658836/19558276/8bbfeaf4-9697-11e6-9822-f16a6e6e3476.png)

'numParcela' = 0  for all results (in this case)

so, if we assume that when there is a negative value for an specific 'document_number' is a case of not using the ticket, the result is an expense of refunds fee. And in this case, an analysis of how many tickets are returned and how much that costs for each Deputy in refunds fee would be really interesting.

**Comment by victorgcapone** [comment]
I was thinking why the vlrDocumento and vlrLiquido have the same negative value, I mean, it's ok if we have positive values, you could be paid less than what you spent because of the remark and reimbursement values, but if your document_value is negative, it means that you received that money(from the airline company) and since net_value is calculated subtracting the remark and reimbursement values from the document value, I think the net_value is negative only because of this calculation.(Since remark and reimbursement are 0)

All this because there are cases in which summing up all the net values from a same document_number gives us a negative total, which I am not yet sure of what means.It is as if the congress person would buy the ticket but not try to use the quota but would register it when it got canceled.
![captura de tela de 2016-11-01 20 51 29](https://cloud.githubusercontent.com/assets/5949575/19910563/fdfb0414-a074-11e6-8579-704d59fa708c.png)

**Comment by cuducos** [comment]
Just as an option, I would suggest asking the Lower House for clarification. They have a [contact form](http://www2.camara.leg.br/participe/fale-conosco) that generates a protocol (we can make some pressure with the protocol if they don't reply) and (from [my experience](https://www.reddit.com/r/brasil/comments/4xyy0s/dúvidas_sobre_a_cota_para_o_exerc%C3%ADcio_da/)) they are very thoughtful in responding to the public.

**Comment by c4rl0sm3nd3s** [comment]
I was kind offline, so here it is the answer.

So, it will be possible to calculate at least the fee for canceling the ticket as a new type of expenses. Could be the most irresponsible type of expense, because if you buy and cancel a lot, it is because you dont care about planning :) 

[resposta.pdf](https://github.com/datasciencebr/serenata-de-amor/files/704631/resposta.pdf)

**Comment by Irio** [comment]
Question already [answered](https://github.com/datasciencebr/serenata-de-amor/issues/29#issuecomment-272468853) by @c4rl0sm3nd3s and in https://github.com/datasciencebr/serenata-de-amor/pull/134. Closing.
