### ISSUE TITLE
Clarify Docker instructions

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/serenata-de-amor#292]
I can get notebooks running with `docker-compose up` but our `CONTRIBUTING.md` guide instructs me to enter yet another command: `docker-compose run --service-ports research jupyter notebook`.

It'd be great to clarify **when** and **why** the second command, added in #287, is needed: does it depends on the OS? On the OS settings? On Docker or Docker Compose versions? Etc.

**Comment by giovanisleite** [comment]
I followed @anaschwendler steps described at #274 but removing `--service-ports`, it worked as expected.

Running the jupyter command `docker-compose run --service-ports research jupyter notebook` after `docker-compose up -d` gets an error, `Bind for 0.0.0.0:8888 failed: port is already allocated`.

So, I followed with `docker-compose down` and `docker-compose run --service-ports research jupyter notebook` and it worked.

In my case, the `up` command already expose the ports and the steps at readme wouldn't work.

**Comment by anaschwendler** [comment]
So, that was a thing that I was looking and was having some problems, but as long it seemed to be working I just followed, because in the first time that I had run, I needed to run the `--service-ports` command. But then, it was no longer needed.

I think that now it is no longer needed :)

> In my case, the up command already exposes the port and the steps at readme wouldn't work.

That is the same for me too!
