### ISSUE TITLE
Captcha for the CNPJ

### ISSUE THREAD

**Issue by jaysonsantos** [datasciencebr/serenata-de-amor#42]
Is it illegal to break the captcha on Receita's website? If it is not maybe I can share a project that I did using scikit-learn.

**Comment by montenegrodr** [comment]
@jaysonsantos I guess not. Well, at least it is not a big deal, since many Brazilian companies sell it as service/product. Do you have annotated data for that?

**Comment by jaysonsantos** [comment]
@montenegrodr drop me an email and i can share what I have with you and maybe you can use it.

**Comment by montenegrodr** [comment]
@jaysonsantos montenegrodr at GMAIL

**Comment by caduvieira** [comment]
According to the 8.777 / 2016 decree the Ministry of Finance must open the CNPJ data up until november 11th http://www.planalto.gov.br/ccivil_03/_Ato2015-2018/2016/Decreto/D8777.htm

**Comment by jaysonsantos** [comment]
Hi all, i've published the code here https://github.com/jaysonsantos/captcha-breaker

**Comment by augusto-herrmann** [comment]
That is a [high value dataset](http://index.okfn.org/place/brazil/companies/) that unfortunately isn't open yet in Brazil.

At least there are some other sources for company data. Incomplete, but still could be useful.

[OpenLEIs](http://openleis.com/) has [1047 Brazilian companies](http://openleis.com/legal_entities/search/registered_country_code/BR). Companies that trade assets publicly abroad (such as the NYSE) are legally required to register for a LEI, which is an international legal entity identifier. This dataset is already open.

The voluntary federal fund transfer system (Siconv) has a daily updated [open data API](http://dados.gov.br/dataset/siconv) with some [43962 legal entities](http://api.convenios.gov.br/siconv/v1/consulta/proponentes.html). These are mostly city council public bodies and non-profits civil society organizations. However, it might be useful to include those in the database to detect possible cases where a politician might use an NGO's legal entity to be reimbursed for a fictional expense.

The federal government's procurement system also has an [open data API](http://dados.gov.br/dataset/compras-publicas-do-governo-federal). If a company has done business with the federal government or has registered itself to be able to participate in procurement at some point in its life, it is on the supplier registry (SICAF). Unfortunately, the API's data has not been updated since 2015, however, its registry of [333977 legal entities](http://compras.dados.gov.br/fornecedores/v1/fornecedores.html) ought to be useful.

**Comment by tomascamargo** [comment]
@caduvieira do we have any update on the status of the Decreto 8.777, will the Receita release such information?

**Comment by caduvieira** [comment]
Not yet. I open a LAI request but I don't have a response yet.

**Comment by Irio** [comment]
Based on the conversations I had at [CGU](http://www.cgu.gov.br/) this week, Federal Revenue is probably far from publicly sharing their databases (regardless the existence of this decree). We can and should open a official request, but start discussing alternatives is already welcome.

@caduvieira Can you post the request number so we can follow the progress with you?

**Comment by caduvieira** [comment]
The request was already denied. I asked for a review and I am waiting for a response. They claimed that they don't have the technology to open the data. 
https://esic.cgu.gov.br/sistema/Pedido/DetalhePedido.aspx?id=UX6bMBnVD30=

[ESIC Report](https://github.com/datasciencebr/serenata-de-amor/files/601045/report.pdf)

**Comment by caduvieira** [comment]
Meanwhile we could use the https://www.receitaws.com.br/ for check data

**Comment by cuducos** [comment]
> Meanwhile we could use the https://www.receitaws.com.br/ for check data

That's [what we're doing](https://github.com/datasciencebr/serenata-de-amor/blob/19f7b603e0b396b1be27f62c901849c481d83cd4/src/fetch_cnpj_info.py#L71) ; )

**Comment by cuducos** [comment]
Closing this: ReceitaWS is already in use and recently started [to offer data that was missing (partners list)](https://github.com/datasciencebr/serenata-de-amor/issues/16#issuecomment-286167555).
