### ISSUE TITLE
Document available datasets

### ISSUE THREAD

**Issue by Irio** [datasciencebr/serenata-de-amor#51]
Preferably in the README itself. What data we currently have? How to find out more about each variable?

Comes to better answer questions like @rafaelalmeida's here: https://github.com/datasciencebr/serenata-de-amor/issues/39#issuecomment-246122729.

**Comment by Irio** [comment]
Complementary to this one, I'm working on @cuducos' pull request generating a Markdown document the main dataset we've been working these days, https://github.com/datasciencebr/serenata-de-amor/pull/25.

**Comment by cuducos** [comment]
And yet anther complement, we might want to document what each script inside `src/` does. @irio have you raise this issue thinking of taking it over? I can try sending a PR on that until Monday.

**Comment by Irio** [comment]
@cuducos I'm generous enough to distribute issues with anyone who wants one. 😄

**Comment by cuducos** [comment]
I’d suggest adding it to `CONTRIBUTING.md` instead of `README.md`. When we discuss the purpose of each directroy, I think we can add a sub-section explaining more about the datasets, and one subsction to explain the purpose of each  script in `src/`.

Anyway, gonna send a PR soon and copy and paste makes it easy to move the contents around ; )

**Comment by cuducos** [comment]
And I also believe it makes no sense to have _Public Data Lists and Strategies for Mass Collection_ in `README`s anymore. All those ideas are recorded and discussed into Issues now.
