### ISSUE TITLE
Why python(2) instead of python3?

### ISSUE THREAD

**Issue by Bilkow** [datasciencebr/serenata-de-amor#59]
As the project is still relatively small, it is easier to port. Why start in python2 if the '\_\_future\_\_' is already here?

**Comment by cuducos** [comment]
Worry not, my friend. We're using Python 3. In the `CONTRIBUTING.md` when we create the environment from Conda, we especify the version 3 ; )

**Comment by Bilkow** [comment]
Oh, great! But shouldn't the shebang line specify python3 as the interpreter? (on line 1 of the setup file: `#!/usr/bin/env python` I __believe__ it should be `#!/usr/bin/env python3`)
In my system, specifying only python ends up in python2.

**Comment by cuducos** [comment]
Hum… reopening the Issue!

@irio is this a problem? We could change the way we call `setup` in the instructions (I guess that's the file you're talking about, @Bilkow, am I right), because shebangs really rely on a very unstable stack: how each of us set up our own computers. Maybe say that the _recommended_ way is to run `python setup.py` with Python 3.

Or (re)write/(re)check setup in a way that is compatible with Python 2 and 3…

**Comment by cuducos** [comment]
Or… `/usr/bin/env python` within the project environment created (check CONTRIBUTING.md) will always be Python 3? Not sure… gonna check that later (but if anyone knows the answer, save me some minutes).

**Comment by flaviodrt** [comment]
@cuducos the project environment will always be Python 3
The python path will be like: `/home/user/anaconda/envs/serenata_de_amor/python` which is Python 3, but I don't know if the setup script will use Python from Anaconda env or `#!/usr/bin/env python`

**Comment by cuducos** [comment]
> I don't know if the setup script will use Python from Anaconda env or #!/usr/bin/env python

That's my doubt too.
