### ISSUE TITLE
What do you think about these metrics?

### ISSUE THREAD

**Issue by henriqueutsch** [datasciencebr/serenata-de-amor#62]
https://gist.github.com/henriqueutsch/f74572e8c18d92bb5c3f

**Comment by cabral** [comment]
Hi Henrique! Very interesting contribution.

Was wondering what is your goal with this issue. My guess is that you want to create a metric system (in Machine Learning terms, new "features") inside Serenata de Amor. If it's, could you explain it a bit more?

**Comment by ruivelocci** [comment]
I see here a good way to think because Blockchain could make huge revolution in 10 years or less. Smart Contracts - [explain](https://smartcontract.com/) - is that awesome idea. All contracts have the same validation used in bitcoins.
Line 79: Usar o mesmo esquema de bitcoin pra validar os dados da nota, quanto mais auditorias mais confiável são os dados.

**Comment by ruivelocci** [comment]
It's a starting point i guess.

**Comment by cuducos** [comment]
Any progress here in the sense of making this metrics more tangible? I agree with @cabral: _could you explain it a bit more?_

**Comment by cuducos** [comment]
Closed by inactivity, but anyone is free to reopen the discussion here — I reopen the _issue_ if that's the case ; )
