### ISSUE TITLE
Some metadata could be in git repository

### ISSUE THREAD

**Issue by josircg** [datasciencebr/serenata-de-amor#74]
It would be faster to identify field structure when analysing Jarbas result like this one:

http://jarbas.datasciencebr.com/#/document_id/5813842/

where "month" and "year" were not well documented.

Suggestion: add to repo data/YYYY-MM-DD-ceap-datasets.md

**Comment by cuducos** [comment]
Hi @josircg!

Good point. For those working with data analysis, it is supposed to be in `data/2016-08-08-ceap-datasets.md` — this file is created by  [`src/translation_table.py`](https://github.com/datasciencebr/serenata-de-amor/blob/master/src/translation_table.py), as described in our [contributing guide](https://github.com/datasciencebr/serenata-de-amor/blob/master/CONTRIBUTING.md#quota-for-exercising-parliamentary-activity-ceap).

However, for those just verifying the suspect documents/receipts, for those working with communication, and for anyone not running the full data science stack this file could be more accessible.

What do you all think about two possibilities:

* Linking the [original source in Portuguese](http://www2.camara.leg.br/transparencia/cota-para-exercicio-da-atividade-parlamentar/explicacoes-sobre-o-formato-dos-arquivos-xml) in Jarbas and in this repo (letting the reader to deduce our translation)
* Saving `2016-08-08-ceap-datasets.md` outside the `data/` adding it to the repo (and, if so, where should we place it, and how to name it)

**Comment by Irio** [comment]
Hi @josircg, that's a question I asked myself when finishing the [related pull request](https://github.com/datasciencebr/serenata-de-amor/pull/25). The reason why I put it in the gitignored folder is because the documentation belongs to an specific version of the datasets (versioned by the date in the file name). In the same way we don't commit datasets (since we will soon have many version of different datasets), we're not committing their documentation.

For addressing your use case, I would add the dataset documentation (contained in the `data/YYYY-MM-DD-ceap-datasets.md` in Jarbas' web interface. Would that help you?

**Comment by cuducos** [comment]
Good point too, @irio. Gonna add this Issue to Jarbas and close this one here on Serenata — is that ok?

**Comment by josircg** [comment]
For an end-user, the link to the original source in Portuguese in Jarbas web interface would be suffice. 

The developer will get the .md file when he/she download the dataset.
