### ISSUE TITLE
Por que não em português?

### ISSUE THREAD

**Issue by oxydron** [datasciencebr/serenata-de-amor#87]
- O projeto nasceu por conta da corrupção no **Brasil**
- Acredito eu que maior parte dos participantes do grupo no Telegram sejam **brasileiros**
- Regularmente, as pessoas escrevem uma palavra em português entre aspas ou por não saber traduzir-la ou porque não tem tradução.
- muitas vezes saem frases em inglês incorretas, por falta de domínio/uso diário da língua por muitos

Então porque não conversarmos simplesmente em português?
Ou em vez disso, criar um grupo do Telegram para discussões em português?
Ou realmente, mudar de plataforma para conversação, como proposto em #81 #46 ?
Eu realmente acho que é importante facilitarmos a comunicação entre nós, e acho que isso é melhor alcançado ao usarmos nossa língua nativa para tal.

**Comment by Scoppio** [comment]
Vou responder em português e em inglês
-  O projeto nasceu por causa da corrupção no Brasil, no entanto o PROJETO é universal, open source, qualquer um pode participar sem restrição de boras, e um projeto só é universal se a lingua de sua documentação for universal. Felizmente a lingua "universal" é o inglês, e não o francês (sério... francês é muito difícil :( ).
- A maior parte dos participantes no Telegram são Brasileiros, no entanto o grupo no Telegram é internacional, e a inclusividade exige o uso de lingua franca, que no caso é o inglês
- Se a pessoa não sabe traduzir alguma palavra, não tem problema, outras pessoas podem atuar na tradução, a pessoa que não sabe a palavra pode aprender com a ajuda de outras. Podemos criar um dicionário de traduções "complexas", como termos economicos e políticos.
- Não tem problema frases incorretas em inglês, estamos todos aprendendo, e a prática leva à fluência. Se não praticarmos desenvolver nossos projetos em inglês, documenta-lo em inglês, ficaremos restritos ao nosso "mundinho", lendo só livros que editoras publicaram em portugues, assistindo palestras que legendaram em português, trabalhando só em projetos brasileiros e para empresas no Brasil e com clientes brasileiros.

Criar um grupo de discussões em português é ruim pois vai criar branches nas discussões, o que um grupo "ja resolveu" pode estar em discussão no outro grupo, teremos dois projetos paralelos e não mais apenas 1.

E usarei um pouco de choque de realidade aqui... dificilmente seremos "bons desenvolvedores" se estamos limitados à língua portuguesa. Maior parte do material de aprendizado e das documentações de nossas ferramentas está em inglês, saber inglês TÉCNICO é tão importante quanto saber programar um "teste fizzbuzz".

**Comment by Scoppio** [comment]
The project was born because of Brasilian corruption, but the PROJECT is universal, open source, anyone may take part on it without border restrictions, and a project can only be universal if the language of its documentation is universal. Fortunatelly this "universal" language is english, not french (really... french is sooo hard :( ).
Most of the users at Telegram are Brasilian, but the group is international, and the inclusiviness needs the use of a lingua-franca (this is the correct term ;) ), which is english.
If the person don't know how to translate a word, it is not a problem, other people may act and translate it, he may learn with others. We can create a dictionary of complex translations, such as economy and politic terms.
There is no problem writting bad english, we are learning, and pratice takes us to fluency.
If we don't pratice to develop our projects in english, document it in english, we will be restrict to our "little world", reading only books that were published in portuguese, watching only portuguese lectures, working on brasilian projects to brasilian companies with brasilian clients.
Create a discussion group in portuguese is bad because it will branch the discussion, what one group´may have already concluded, the other may still be discussing, we will end up with paralel projects instead of working on the same.

And a little bit of reality chock here... we won't become "good developers" if we are limited by the portuguese language. Most of the learn material and documentation of our tools of trade are in english. To know a technical level english is as important as know how to do a "fizzbuzz test"

**Comment by c4rl0sm3nd3s** [comment]
Acho que o projeto pode ser open source, mas dificilmente sera facil de aplicar em outro governo no mundo. Eh mto especifico para a realidade brasileira. 

e outra, discutir ideias eh diferente de escrever o codigo fonte. Fica muito mais natural falar a lingua que domina qdo se trata de ideias.

meus 2 centavos

**Comment by Scoppio** [comment]
No entanto, Carlos Mendes, o projeto ainda é um portifólio OBSCENAMENTE BOM para todos os participantes, e sinceramente, eu gostaria que meus futuros contratantes ou clientes olhassem esse projeto, lessem sua documentação e falassem "NOSSA, você participou disso... caralho!"

**Comment by c4rl0sm3nd3s** [comment]
o projeto = codigo fonte = ingles 
ideias = telegram = portugues
foi isso que quis falar

**Comment by ayghor** [comment]
O projeto é para atender a comunidade ou construir um portifólio? =op

**Comment by Scoppio** [comment]
Ayghor, o projeto atende a comunidade enquanto constrói um histórico de desenvolvimento, aka.: portifolio.

Você não sabia que coisas boas beneficiam a todos em vários fronts?

**Comment by ayghor** [comment]
Sei, mas o intuito é atender a comunidade ou construir um portifólio?

**Comment by ayghor** [comment]
btw, se a decisão de ser em inglês ou português for tomada visando benefício individual, entendo _corrupção_. =op

**Comment by Scoppio** [comment]
O intuito seu, o do cuducos, do Carlos Mendes, do oxydron ou o meu?
O meu intuito é trabalhar em um projeto open source bom de data science para ganhar experiencia e que de preferencia minha participação no trabalho traga resultados positivos para a sociedade civil. 
Aka.: Quero que o tempo que eu dedique adicione valor.

OBS.: Sugiro que você pare com esse "bike shed argument", causa desgaste desnecessário, pode dar início a um flamewar, além de atolar o email de todos com emails irrelevantes para o projeto e para os participantes do projeto. Sério.

**Comment by ayghor** [comment]
me referia ao intuito da iniciativa. e não sei o que é um "bike shed argument", mas considero as razões para tomada de decisões completamente relevantes.

**Comment by arvanus** [comment]
Please, just respect the ideas of the developers, they created this
project, it's useful for Brazil, and useful as a portfolio to they, Lucas
Coppio are right when he explain the importance of working in English.
Carlos Mendes and Ayghor face this like an opportunity to improve your
English like I`m doing now (I'm from Santa Catarina-Brazil)

PS: You can translate this conversation in this link
http://bit.ly/2epZDKB

2016-10-18 16:41 GMT-02:00 ayghor <notifications@github.com>:

**Comment by Scoppio** [comment]
PT-Br "Bike-shed argument"
Um dia um engenheiro apresentou para um quadro de diretores seu projeto para um reator nuclear enorme que ele queria construir, falou de todos os detalhes, mostrou o conceito do prédio, as áreas, o local que ele planeja, os planos de contenção, a lagoa artificial que seria criada para resfriar os reatores, todo mundo aplaudiu seu projeto, ele então apresentou o projeto de uma cobertura para pararem as bicicletas na frente do prédio, a reunião delongou por HORAS, todos queriam que sua opinião quanto as cores da cobertura, se usariam telhas de zinco ou de plástico, se seria feito em alvenaria ou aço.
O "argumento da cabana de bicicletas" é justamente quando algo que não requer nenhuma expertise gera argumentos longos e sem sentido, que desgastam a todos e não trazem absolutamente nenhum resultado para ninguém.

English "Bike-shed argument"
One day an engineer presented to a board of directors his project for a nuclear reactor he wanted to construct, he showed the all the detais, the concept of the building, the areas, the local he plans to build, the artificial lake to cool it down, everyone applauded his project. He then proceded to show the bikeshed he proposed for the garage, the meeting went for HOURS, everyone wanted his voice to be heard, the color of the walls, the type of the roof, if it is going to be done with bricks or steel.
The Bike-shed argument happens when something that requires absolutelly no expertise generates lenghty and meanless arguments, with no result whatsoever for anyone!

**Comment by ayghor** [comment]
> respect the ideas of the developers

não estou respeitando?

**Comment by c4rl0sm3nd3s** [comment]
Eu nao preciso provar nada pra ninguem.

Manter o codigo fonte, comentarios, read.me etc em ingles acho que eh o ideal, quem quer usar como portfolio usa, quem quiser tentar aplicar isso para outra realidade fora do brasil (boa sorte) pode tbm.

soh acho que manter em ingles a discussao de ideias eh mto elitista. Garanto que muita gente deixa de comentar algo com boas ideias pq se intimida com o ingles.

**Comment by ayghor** [comment]
a escolha de idioma aqui não é uma decisão banal, o inglês dificulta e exclui. um levantamento de quem concorda com inglês/português seria no mínimo esclarecedora.

**Comment by oxydron** [comment]
@Scoppio https://en.wikipedia.org/wiki/Law_of_triviality (aka bike-shed argument). Ou seja, essa issue é irrelevante.

Algumas coisas mais: como pode ser lido na descrição do [Serenata de Amor](https://github.com/datasciencebr/serenata-de-amor), "Our current milestone is to create the means for this kind of automation with the Quota for Exercising Parliamentary Activity (CEAP), from the Brazilian Chamber of Deputies.", logo o projeto não é universal, não ainda pelo menos.

Manter a discussão em inglês é aumentar a abrangência de um assunto brasileiro, enquanto que exclui brasileiros que poderiam ajudar.

**Comment by oxydron** [comment]
Criei um formulário para coletar a opinião do pessoal. Peço para que mantenha essa *issue* ativa até conseguir pelo menos 133 respostas (metade do grupo do Telegram).

https://docs.google.com/forms/d/e/1FAIpQLSd8AoDk7nvcDfo3Zc1rAgrcUpQ4pyrsFtIEdrSZoIMxed_bzA/viewform

**Comment by cuducos** [comment]
Hi @oxydron, @ayghor and @c4rl0sm3nd3s — I'm glad you both raise this issue in a clear manner. Although we have discussed that in many other Issues/PRs/chats, that was not documented anywhere.

And thank you @Scoppio for putting things in such a clear and straightforward way.

I'd add to what Lucas said some more substantial bits:

* **This project has international contributors from day zero**: they don't speak Portuguese and (in opposition to what Carlos said) they strongly believe the algorithms developed here might help them in their home countries — we want to welcome them.
* **International standard and impact**: English is a standard for software development in the global market and we believe that the fight against corruption is not inherent to Brazil, we want to be a player in the big scene so we do all the technical part in English (that includes code and discussions that take place in Telegram, the technical group; note that we have the Facebook community for the non-technical public and it is in Portuguese).
* **Media impact**: We also believe that the international media might be interested in our reports, and we assume that international exposure can be a strong ally in fighting corruption in our homeland; keeping the analysis documents and discussions in English make the knowledge and findings available and accessible to a bigger amount of people if they are in English (not in Portuguese). And we assume that the local journalists of the biggest media outlets have enough English knowledge to follow our English notebooks.
* **Transparency**: Transparency is also a strong ally; if the credibility of out codebase and analysis is called into question, people not related to Brazil and can easily act as external auditors following our steps and assuring everything is on the right track — having the code, the technical discussion and documentation will be at hand for anyone in the world that want to audit our work.

That said I strongly recommend us to keep code, GitHub and Telegram in English (and at the same time I have nothing against using Portuguese in the Facebook group).

**Comment by ayghor** [comment]
@oxydron pode acrescentar as seguintes perguntas?

 * lingua nativa?
 * idioma preferido para documentação?
 * idioma preferido para discussão?

**Comment by pedrolucasoliva** [comment]
Can I join the telegram group?

**Comment by arvanus** [comment]
Suggestion, adds an option to the question "Do you think Telegram is the
best platform to meet the community for discussion?"


   - Whatever


I never really used the telegran, but nothing prevents me from using it, so
what is set for me is good


Sugestão, adiciona uma opção para a pergunta "Você acha que o Telegram é a
melhor plataforma para se reunir a comunidade para discussão?"

   - Tanto faz

Eu realmente nunca usei o telegran, mas nada me impede de usá-lo, portanto
o que for definido, para mim está bom

**Comment by c4rl0sm3nd3s** [comment]
pra quem perguntou. o grupo do telegram: http://bit.ly/2cUBFr6 

soh nao achei o link do grupo no facebook. 

nao me importo em escrever em ingles, mas se tem um grupo onde as pessoas trocam ideias em portugues, eu prefiro.

**Comment by cuducos** [comment]
So basically the strategy is to exclude non-Portuguese speakers from the Portugese written poll that was set to try to convince us to communicate in Portuguese, isn't it?

If that's the case, I can't help but say it'd be biased.

**Comment by ayghor** [comment]
@oxydron você tem que incluir as perguntas em inglês também, o @cuducos tá certo hu3

**Comment by cuducos** [comment]
@c4rl0sm3nd3s Facebook link is at http://serenata.datasciencebr.com

@pedrolucasoliva Telegram link is at `CONTRIBUTING.md`

**Comment by oxydron** [comment]
@cuducos sim, irei traduzir o questionario. Quanto ao que você escreveu, concordo com tudo menos a conversação no Telegram ser em inglês. O fator mais relevante pra mim foi o que você disse quanto a imprensa internacional ter interesse.

**Comment by oxydron** [comment]
Questionário traduzido (da melhor forma possível em alguns minutos :P )

**Comment by oxydron** [comment]
The new questionaire: https://goo.gl/forms/6SpLUENjRaVxn6Ew1

**Comment by cuducos** [comment]
> @cuducos I think the data collected from this questinarie should clarify the opinion from most and to end this discussion.

Honestly I doubt it. IMHO this is mostly a matter of qualitative reasoning than quantitative measuring. In other words the majority of people following this topic (here or elsewhere) will vote in a few clicks, in a few seconds without taking into account the complexity underneath each decision — take a look in [the case about results per page in Google](http://glinden.blogspot.com.br/2006/11/marissa-mayer-at-web-20.html) and let me know if it makes sense, buddies.

**Comment by oxydron** [comment]
Results for those interested.

https://docs.google.com/spreadsheets/d/1Jd4fxw-qJSGKw1-Hm_MRbsEtYBxF-SasjWmO63V8KC0/edit?usp=sharing

**Comment by Scoppio** [comment]
Oxydron, one small tip:
Never use piecharts, they are not good to compare percentage. People are barely able to comprehend any difference in betwen 30% and 40% in the piechart, they may look statistc'ish but instead they just create confusion. Bad bad way to expose data.
