### ISSUE TITLE
How Can I to contribute?

### ISSUE THREAD

**Issue by mlordelo** [datasciencebr/serenata-de-amor#90]
Hi, I'd like to contribute in this project, but I don't know Python as well. How can I start to contribute? There is some initial guide of the project?

PS: Sorry, my english isn't good...

**Comment by Scoppio** [comment]
Hi mlordelo,
I have a different "twist" here, I am good in Python, but I don't know where to start to contribute :D

**Comment by joaomluz** [comment]
I am in the same page.. i know a little about python but want to help this project. Do you guys have a starting guide?

**Comment by leobiscassi** [comment]
Hi all, I'd like suggest a thing to help with this. If maintainers add labels with level required to solve each issue will be cool for new contributors, like this:[https://github.com/galaxyproject/galaxy/labels/friendliness%2Fintermediate](https://github.com/galaxyproject/galaxy/labels/friendliness%2Fintermediate)

**Comment by mlordelo** [comment]
I liked the suggestion. With labels, we can try to do something.

**Comment by leobiscassi** [comment]
yeah, it's more easy.
I'm beginner contributor in the galaxy project and this helps a lot. Well, thi is my 5 cents in this discussion :grin:

**Comment by cuducos** [comment]
Hi @mlordelo — welcome!

For technical contributions we have [`CONTRIBUTING.md`](https://github.com/datasciencebr/serenata-de-amor/blob/master/CONTRIBUTING.md), have you checked it? The link is on the main page and also in a yellow box when you open a new issue ; )

In that document, if you take a look into the _Four moments_ table you can see that no technical knowledge is needed at all in certain moments. Make yourself at home ; )

If you — and @Scoppio — still have doubts after reading it, can you give us more specific feedback on how to improve this document?

If your problem is only Python, you can code in other languages. There are [people coding in R, for example](https://github.com/datasciencebr/serenata-de-amor/pull/52).[Jupyter Notebooks](http://jupyter.org) accepts many languages; feel free to open an issue so we can help you get started in any of them. 

And yet this is just the _technical_ forum. We have a general public forum as a Facebook group — check the [project website](http://serenata.datasciencebr.com) for the link ; )

---

**About @leobiscassi's idea about labels**: not sure how to ponder on the difficulty of each issue. For example, I'm kind of experienced in development, so issues regarding general scripts, tests, setup tends to be easy for me, it would mean I would mean most of these would be `easy` or `medium`. However I never played around with Pandas, or Altair, or Seaborn, nor with scrapping… so analysis or data collection, even if I'm an intermediate/advanced Python developer, would be `hard` for me. Anyway, if you wanna discuss that further let's open an issue for that and we might find a good solution together ; )

**Comment by leobiscassi** [comment]
Hi @cuducos, indeed. In fact, I think this idea is helpful to us if issues will be labeled in [area-label][level] like the example which I give previously, what you think about this?

**Comment by leobiscassi** [comment]
@cuducos :+1:

**Comment by mlordelo** [comment]
Hi @cuducos !

Thanks for the explanations. I confess that I didn't read. I am new here in Git and I'm a little lost about how works.

I will read, thanks!

**Comment by gregoryfm** [comment]
@cuducos I read  [`CONTRIBUTING.md`](https://github.com/datasciencebr/serenata-de-amor/blob/master/CONTRIBUTING.md), but I felt lack of information on how to configure the project on my pc.

For example:
Step 1 fork the project
Step 2 clone the project
Step 3 I don't know.. What I do now? 

Thanks

**Comment by cuducos** [comment]
@mlordelo good news then ; ) Thanks for letting us know.

@gregoryfm well… this kind of information is basic what we tried to share in [The Basic](https://github.com/datasciencebr/serenata-de-amor/blob/master/CONTRIBUTING.md#the-basic) (fork and contribute), and [The Environment](https://github.com/datasciencebr/serenata-de-amor/blob/master/CONTRIBUTING.md#environment) (first and second section of the contributing guide). There we have a neat ordered list of instructions:

> Fork this repository
Create your branch: `$ git checkout -b new-stuff`
Commit your changes: `$ git commit -am 'My cool contribution'`
Push to the branch to your fork: `$ git push origin new-stuff`
Create a new Pull Request

And just a few lines after that:

> `$ conda update conda`
`$ conda create --name serenata_de_amor python=3`
`$ source activate serenata_de_amor`
`$ ./setup`

But from your message I got that this is not clear enough — maybe we shouldn't have split it in two sections. I'm gonna address your questions and if you can get started can you help us clarify this instructions for newcomers? It's very important for us to make this setup as easy as possible. 

---

> For example:
Step 1 fork the project
Step 2 clone the project
Step 3 I don't know.. What I do now?

From this point you should follow the instructions from _The Environment_ (install Anaconda, `conda update conda` etc.).

> Which version of anaconda is used, to Python 3.5 or Python 2.7 version?

Python 3 (and let Anaconda decide the minor version). It's set when you crate an environment: `conda create --name serenata_de_amor python=3` (in other words the `python=3` part of that command specifies the Python 3 runtime).

**Comment by gregoryfm** [comment]
@cuducos Thanks, worked. 

I will send the changes to [`CONTRIBUTING.md`](https://github.com/datasciencebr/serenata-de-amor/blob/master/CONTRIBUTING.md) page.
